### ISSUE TITLE
Support symbols

### ISSUE THREAD

**Issue by jdillworth** [tommasongr/nova-vue#16]
First, thanks for creating this plugin!

Sorry if I'm just doing something wrong but when I use the `Go > Go to Symbol..` menu option I would expect to see methods, computed properties, and life-cycle methods (created, beforeDestroy). Instead I see script, template and sometimes some template tags with their CSS class names.

Is symbol support missing? If so, are you planning to implement it?

**Comment by tommasongr** [comment]
Hi there! Thank you too for enjoying it!

Symbol support is something I'm aware is not the best, unfortunately is not completely under my control. Vetur which is the Vue file parser and is running under the hood doesn't provide such information, at least as far as I've found. The symbols you are seeing right now come from the syntaxes definitions of Nova. That means that in order to display that kind of information I would have to overwrite the standard js definition of Nova... Another option would be to define them programmatically with the API but I would have to parse the file another time looking for all the elements...

So far it hasn't been a priority but I can consider working on it for the next release.

**Comment by frufin** [comment]
Right, this would be a really usefull improvement !

**Comment by tommasongr** [comment]
I checked the status of this issue and I'm not sure how the situation was when @jdillworth opened it but now the symbols are almost all available.

The problem with life-cycle callbacks si that the JS syntax doesn't define symbols for object shorthands. Unfortunately Vue best practices require them...

For @logancollins maybe a future release of Nova can fix this 😉

Standard function:
<img width="666" alt="Schermata 2021-03-08 alle 16 57 42" src="https://user-images.githubusercontent.com/25225746/110346760-2c99e200-8030-11eb-9a67-678639385365.png">

Object shorthand (missing symbol):
<img width="802" alt="Schermata 2021-03-08 alle 16 58 01" src="https://user-images.githubusercontent.com/25225746/110346816-3c192b00-8030-11eb-8316-cbc8af6226d0.png">

**Comment by tommasongr** [comment]
Not sure what version of Nova fixed this but in Nova v7.0 object shorthands work as expected 🚀
