### ISSUE TITLE
Implementing Vue LSP

### ISSUE THREAD

**Issue by tommasongr** [tommasongr/nova-vue#3]
I'm trying to implement the Vue Language Server, unfortunately I didn't get that far.

First of all the custom Completions for Vue and the standard Completions for html and css are not shown anymore. Javascript syntax has improved a little bit but not significantly improvements to vue. For example `this` doesn't offer intellisense as it should. I have no clue on how to implement a correct version of this 😕

If anyone can help me, I'd really appreciate it 🙏

@apexskier I've seen that you worked on a similar thing for typescript. Would you mind taking a look at it?

**Comment by apexskier** [comment]
Hey, happy to help out and take a look. Sounds like you've tried something so far - can you share the branch you're working off of?

**Comment by tommasongr** [comment]
Thanks you so much! Here it is: https://github.com/tommasongr/nova-vue/tree/vue-lsp

**Comment by apexskier** [comment]
The first thing I see is
```
Vue[17:01:15.944000] Error: Could not find an executable for process: /Users/cameronlittle/Dev/nova-vue/Vue.novaextension/node_modules/vls/bin/vls
```

because the extension's not [running a self-install](https://github.com/apexskier/nova-typescript/blob/d12ff4b0af6805a8c0020ee14bd0e6b9f2820a63/src/main.ts#L25-L48), like [mine does](https://github.com/apexskier/nova-typescript/blob/master/CONTRIBUTING.md#extension-dependencies). (I use [shrinkwrapping](https://docs.npmjs.com/cli/shrinkwrap), which I'd recommend over a second package-lock.json, since it's intended for publishing like this. There's no effective difference, but I feel it makes it more obvious what's going on) (looks like your language server [has a ton of dependencies](https://github.com/vuejs/vetur/blob/master/server/package.json#L23-L54), which is a bit annoying)

After installing, it looks like the language server starts up with no issues. I'd recommend [naming it something different than "Vue"](https://github.com/tommasongr/nova-vue/blob/vue-lsp/src/Scripts/main.js#L29) to differentiate extension console output between your extension and the language server. (I don't get any functionality off the bat because a `.vue` file isn't automatically recognized as using Vue syntax - I needed to change it from plain text manually. I think this is because I'd opened the file before loading the extension,)

<img width="414" alt="Screen Shot 2020-09-16 at 17 09 38" src="https://user-images.githubusercontent.com/329222/93356399-69360f00-f83f-11ea-83d1-2baabe71ce35.png">

It looks like the language server is doing something... this suggestion isn't provided without it.
<img width="197" alt="Screen Shot 2020-09-16 at 17 11 59" src="https://user-images.githubusercontent.com/329222/93356706-cdf16980-f83f-11ea-9a87-e92d56cba5e6.png">

---

> For example `this` doesn't offer intellisense as it should.

Note that nova doesn't offer suggestions immediately after typing `this.`. It currently requires you to type at least one other character as well (https://dev.panic.com/panic/nova-issues/-/issues/1464, https://github.com/apexskier/nova-typescript/issues/30). Also note that Nova doesn't yet support a bunch of LSP commands natively ([although I think they're planning on improving this](https://dev.panic.com/panic/nova-issues/-/issues/1534#note_7620)). Most of my typescript extensions's functionality is [manually implemented](https://github.com/apexskier/nova-typescript/tree/master/src/commands).

---

> First of all the custom Completions for Vue and the standard Completions for html and css are not shown anymore.

I'm not sure what the custom completions are supposed to be doing, but I definitely see new completions coming from the language server. I've only played with nova completions a tiny bit, but I wouldn't be entirely surprised if running a language server conflicted with other custom defined completions from the same extension.

<img width="182" alt="Screen Shot 2020-09-16 at 17 33 48" src="https://user-images.githubusercontent.com/329222/93359352-cc757080-f842-11ea-9865-1100e6474cb1.png">

**Comment by tommasongr** [comment]
Thank you so much for your time and feedback!

Thanks for the suggestions of using shrinkwrapper, i'll definitely merge your pull request #4

---

> It looks like the language server is doing something... this suggestion isn't provided without it.

Yes I saw that, what I ment was that on vscode for example the suggestion for `this` includes a lot of stuff coming from the vue instance.

---

These are some completions that I defined specifically for the vue-html subsyntax.

<img width="568" alt="Schermata 2020-09-16 alle 18 56 55" src="https://user-images.githubusercontent.com/25225746/93368550-6c84c700-f84e-11ea-8262-166baf911cd0.png">

The LSP overtooks them and provides these instead

<img width="564" alt="Schermata 2020-09-16 alle 18 59 30" src="https://user-images.githubusercontent.com/25225746/93368930-e87f0f00-f84e-11ea-8a8a-dcb77c8782f9.png">

Nothing wrong until you confirm and... it escapes and places `$1` inside the brackets. I suppose this is the vscode syntax for placeholders in completions. This occurs not only in html but also in every other completions provided by the LSP.

<img width="442" alt="Schermata 2020-09-16 alle 18 59 42" src="https://user-images.githubusercontent.com/25225746/93368986-faf94880-f84e-11ea-8308-d5a35c6b1bc3.png">

---

Also the standard completions for other things like css are gone

Expected:
<img width="408" alt="Schermata 2020-09-16 alle 19 09 33" src="https://user-images.githubusercontent.com/25225746/93369950-65f74f00-f850-11ea-816b-d37baaf02ef1.png">

Actual:
<img width="432" alt="Schermata 2020-09-16 alle 19 10 04" src="https://user-images.githubusercontent.com/25225746/93369995-73143e00-f850-11ea-85a0-dbbd5345be8d.png">

Maybe @panicinc can take a look on this?

**Comment by yoyo930021** [comment]
Hi, I'm a Vetur project contributor.

I work in this issue.
It can solve many dependencies problem.
https://github.com/vuejs/vetur/issues/2233

Maybe you can wait this issue.
I will try to help when issue finished.

**Comment by tommasongr** [comment]
It would be great! Thanks for your contribution! @yoyo930021

**Comment by apexskier** [comment]
> Nothing wrong until you confirm and... it escapes and places `$1` inside the brackets. I suppose this is the vscode syntax for placeholders in completions. This occurs not only in html but also in every other completions provided by the LSP.

I see... I think this is something we'll need Panic to solve.

The LSP does have [support for completion placeholders](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#placeholders). It [kind of looks like Vetur's language server is generating placeholders](https://github.com/vuejs/vetur/blob/8a59a061b0fad47ef25b0c14ddbb4ebe431609ff/server/src/modes/template/tagProviders/componentInfoTagProvider.ts#L22), but I'm not positive. That's something to confirm by inspecting the messages it's sending. If it does, my guess is that Panic hasn't yet added support for them from Nova's side.

**Comment by jonowells** [comment]
> The LSP does have [support for completion placeholders](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#placeholders). It [kind of looks like Vetur's language server is generating placeholders](https://github.com/vuejs/vetur/blob/8a59a061b0fad47ef25b0c14ddbb4ebe431609ff/server/src/modes/template/tagProviders/componentInfoTagProvider.ts#L22), but I'm not positive. That's something to confirm by inspecting the messages it's sending. If it does, my guess is that Panic hasn't yet added support for them from Nova's side.

From the Nova 1.2 Release Notes:
- Extensions: Added support for the LSP Snippet format in completions

**Comment by tommasongr** [comment]
@jonowells I tried yesterday 1.2 updates with the already in place implementation of vls but it still autocomplete with e.g: `v-if="$1"`

@apexskier gives it a try too and found the same issue.

I reached out some folks at Panic and they are looking at it. Let's see

**Comment by laosb** [comment]
Now Nova 2 has been released. Any improvements on this?

**Comment by tommasongr** [comment]
@laosb I started looking at it yesterday evening! The LSP already works. The problem right now is that the LSP overrides the custom defined completions and their completions are not the best to be honest... I'm looking to a way to disable the LSP completion feauture but I'm not sure on how VLS works.

@yoyo930021 Can you help me on this?

**Comment by yoyo930021** [comment]
> @laosb I started looking at it yesterday evening! The LSP already works. The problem right now is that the LSP overrides the custom defined completions and their completions are not the best to be honest... I'm looking to a way to disable the LSP completion feature but I'm not sure on how VLS works.
> 
> @yoyo930021 Can you help me on this?

I can add option for disable LSP completion.
But I don't think `vls` completion would be worse.
After all, we have TypeScript support.

**Comment by tommasongr** [comment]
> I can add option for disable LSP completion.
> But I don't think `vls` completion would be worse.
> After all, we have TypeScript support.

@yoyo930021 sorry about that I guess I didn't explain myself correctly. Is not about what vls has but what it doesn't have. Take a look... This kind of completions are not available in vls and if an LSP is activated the custom completions are not shown.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/25225746/97078007-fdd32000-15e8-11eb-8446-f5b3d52d320a.gif)

However I've been able to show them programmatically through the Nova API. I think I'll rewrite them this way

**Comment by tommasongr** [comment]
Another option it might be to add the completions to the LSP directly but I'm not sure if is it possible with VLS and eventually how to do that. In that case it would be possible to scope the completions to the export default only? and maybe customize them based on the lang type (js, ts, ...)?

**Comment by tommasongr** [comment]
> Now Nova 2 has been released. Any improvements on this?

@laosb Vetur mode has finally landed on Nova! Slap that update button! 🥳

https://twitter.com/tommasongr/status/1320367367596183552

**Comment by tommasongr** [comment]
Since the LSP is implemented I'll close the issue. Thank you all guys!

**Comment by yoyo930021** [comment]
Sorry it's a little late to reply.
I welcome you send a PR to vetur about that snippets.
For example, Javascript can be added here.
https://github.com/vuejs/vetur/blob/master/server/src/modes/script/javascript.ts#L141

It also appears that nova doesn't allow you to use both at the same time.
If two extensions are used, can this problem be solved?
Maybe a similar idea could be the solution.

**Comment by tommasongr** [comment]
@yoyo930021 Thanks! I'll take a look at both strategies!

Anyway can I ask you why intellisense works flawlessly inside script tag but when it comes to the template it doesn't seem to exist at all? I would love to fix that too, thanks

**Comment by yoyo930021** [comment]
> @yoyo930021 Thanks! I'll take a look at both strategies!
> 
> Anyway can I ask you why intellisense works flawlessly inside script tag but when it comes to the template it doesn't seem to exist at all? I would love to fix that too, thanks

I'm not sure what part of intellisense you're referring to in the template.
There are five relevant sections here.
1. HTML5 tag or attrs
> This part is written directly in Vetur.
2. Vue tag or attrs
> This part is written directly in Vetur.
3. External component data provided by library.
> Vetur read `package.json` in project root.
4. Vue components are defined in the file.
> Vetur read `components: {}` in current file, and try to parse them.
5. TypeScript is provided based on the current component.
> When `v-bind`, `v-if`, `v-for`, `{{ }}` in template, Vetur transform template to js code. Provided via typescript.
> This feature is disabled by default. please set `{ "vetur.experimental.templateInterpolationService": true }` to open it.

**Comment by tommasongr** [comment]
@yoyo930021 
> I'm not sure what part of intellisense you're referring to in the template.

As you can see inside the template directives intellisense is not working. This is the only problem I've found for now, everything else works well.

![intellisense](https://user-images.githubusercontent.com/25225746/97558597-9ea44f80-19dc-11eb-93cb-0701ece8dfaa.gif)

**Comment by yoyo930021** [comment]
> @yoyo930021
> 
> > I'm not sure what part of intellisense you're referring to in the template.
> 
> As you can see inside the template directives intellisense is not working. This is the only problem I've found for now, everything else works well.
> 
> ![intellisense](https://user-images.githubusercontent.com/25225746/97558597-9ea44f80-19dc-11eb-93cb-0701ece8dfaa.gif)
> 
> If this is caused by `{ "vetur.experimental.templateInterpolationService": true }` how can I set this command in Nova? And why in vscode I haven't had to set this command to have the feature? Thanks

This is a setting not a command.
In VSCode, it is same as editor config.
VScode will send setting in LSP.

Vetur can send setting when init.
https://github.com/vuejs/vetur/blob/70609ef531ccd1884410ac366b5a3ae08174ceb4/client/client.ts#L56
You can try to use this for test.
But understanding LSP and setting with nova is important.
